### ISSUE TITLE
Non-Accessible colour scheme

### ISSUE THREAD

**Issue by csc207jc** [uoftm/csc207project#20]
Our current colour scheme is very jarring, which makes it harder to use our application.
We should use either a proper high-contrast colour scheme or a more traditional light-mode and/or dark mode view.
![image](https://github.com/uoftm/csc207project/assets/144721194/57d9d4cf-1387-48ac-8655-e98bc5265e2a)

**Comment by csc207jc** [comment]
Personally, I would suggest starting with the outer colour as \#eeeeee and the inner colour as \#dddddd and go from there.

**Comment by uoftm** [comment]
See https://www.refactoringui.com/previews/building-your-color-palette for how to avoid making your page red and yellow :)

**Comment by uoftm** [comment]
Linking #25, that makes customizing the UI a lot easier

**Comment by csc207jc** [comment]
There's been some progress on this issue in terms of layout but some actual colour changes would be great.

**Comment by alexrosen45** [comment]
#34 Seems to resolve this issue since it redefines colours for the entire application.
