### ISSUE TITLE
Email verification regex

### ISSUE THREAD

**Issue by csc207jc** [uoftm/csc207project#22]
Currently, emails are not checked for valid formats and characters.
We should add a Regex to check: 
(1) An email address has an @ sign 
(2) Following the @ sign, there is a valid domain
(3) The email address only has characters allowed in an email address

**Comment by alexrosen45** [comment]
This should still be handled on our end before we send a request to Firebase since it will be much faster.

**Comment by alexrosen45** [comment]
@jcroskery can we get rid of this?

**Comment by alexrosen45** [comment]
There's no need for this now.
