### ISSUE TITLE
Make usernames unique

### ISSUE THREAD

**Issue by csc207jc** [uoftm/csc207project#23]
On signup, we need to query Firebase to ensure the selected username has not yet been taken by another user.

**Comment by alexrosen45** [comment]
We do not need usernames to be unique, we can use the uniqueness of emails instead and leave usernames as a `displayName` in Firebase. See [this](https://firebase.google.com/docs/reference/rest/auth/#section-sign-in-email-password) documentation. #30 handles signup this way and #32 handles login similarily.
